### ISSUE TITLE
when use DeepDTA error

### ISSUE THREAD

**Issue by Golden-proteogenomics** [hkmztrk/DeepDTA#47] opened 2024-07-10 01:33 UTC
hello,
I want to konw when I have finished instation about DeepDTA with direction 'name: deepdta
channels:
  - defaults
dependencies:
  - python=3.6
  - keras==2.1.6
  - tensorflow-gpu==1.15.0
  - scikit-learn==0.22'.

 After that i have the put data folde place in source dirctory.
then, when i run `run_experiments.py`, that will be error that 
![图片](https://github.com/hkmztrk/DeepDTA/assets/50616816/685436dd-d51d-4c21-95e8-b875d103fbac)
,So, I want to konw what can I do for this issue.

**Comment by hkmztrk** [comment] 2024-12-08 18:29
Very sorry for the late reply @Golden-proteogenomics, I hope the issue is resolved by now. Feel free to re-open the issue otherwise.

**Closed as completed by hkmztrk** 2024-12-08 18:29 UTC
